--- #YAML:1.0
name:               MediaWiki-FastDump
version:            0.01
abstract:           Fast and easy access to the pages and titles from a Mediawiki XML dump file. 
author:
    - "Tyler Riddle" <"triddle@gmail.com">
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Scalar::Util:  1.21
    Test::More:    0
    Test::Simple:  0.94
    XML::LibXML:   1.70
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
